### ISSUE TITLE
Nothing happens when running executable

### ISSUE THREAD

**Issue by jojjefern** [m4dEngi/RemotePlayWhatever#122]
Is something supposed to happen when I run the RemotePlayWhatever.exe? I've extracted the folder in my downloaded files. The folder contains the exe and OpenSteamAPI.dll. When I run the exe (as admin), the thinky wheel spins for a sec, then nothing. Am I doing something wrong?

**Comment by m4dEngi** [comment]
It's not supposed to be run as admin. What are your steam and OS versions?

**Comment by jojjefern** [comment]
Ok, I've tried running as non-admin as well

Steam-version:  1694466342
Steam API-version:  SteamClient020
Windows 10 22H2: OS-version 19045.3324

**Comment by m4dEngi** [comment]
Maybe installing latest vc_redist would help  https://aka.ms/vs/17/release/vc_redist.x86.exe

**Comment by Theslippi** [comment]
Been having the same problem myself. been using the app for about a month without issue.As of yesterday  no matter what i seem to do i cant get it to start. i tried installing it on my gaming laptop last night and once again the problem was gone. got home from work today and tried hopping on and it no longer works on my laptop as well now. if anyone comes up with anything pls lmk this app has been soooo helpful.

**Comment by jojjefern** [comment]
> Maybe installing latest vc_redist would help https://aka.ms/vs/17/release/vc_redist.x86.exe

Tried installing it and restarting the computer, still nothing :(

**Comment by JonathanGzzBen** [comment]
@jojjefern this should be closed, latest release fixes the problem

**Comment by jojjefern** [comment]
Same issue now back again. Assuming it's related to new steam client version?

**Comment by m4dEngi** [comment]
Seem to work fine on my end with latest stable client.

**Comment by jojjefern** [comment]
Yep it works agian, not sure what was the problem ¯\_(ツ)_/¯
