### ISSUE TITLE
Dead since new update

### ISSUE THREAD

**Issue by feffom** [m4dEngi/RemotePlayWhatever#137]
It just closes when you click to invite someone. Any help? 

Edit: Worked out of steam beta client, might be dead when it moves to live client.

**Comment by ZeeWanderer** [comment]
The same problem but it worked with the first versions of the family beta steam client version, but stopped working later.

**Comment by m4dEngi** [comment]
I'm sorry, but I don't have enough time now to support the client beta. Maybe in the future.

**Comment by ZeeWanderer** [comment]
It'll eventually be in production so at least identifying the issue may be prudent and as far as i managed to diagnose it - `SendSerializedFunction` and `ClientAPI_Init` function signatures are likely different.

The RemotePlayWhatever application itself crashes on `BCreateRemotePlayInviteAndSession` call due to stack pointer size mismatch i.e. pop/push mismatch. I tried the dumper, but it suffers a segmentation fault due to not finding the mentioned 2 signatures.

I am going to look through the `.so` manually with a disassembler but i don't have much experinece in re-engineering.

**Comment by feffom** [comment]
Hey! No problem at all mate, i just make the topic because it should go live at some point, right? Anyway thats not an obligation for you by any mean. Thanks for your amazing work.
________________________________
De: Borysteam M4dov ***@***.***>
Enviado: segunda-feira, 1 de abril de 2024 00:07
Para: m4dEngi/RemotePlayWhatever ***@***.***>
Cc: feffom ***@***.***>; Author ***@***.***>
Assunto: Re: [m4dEngi/RemotePlayWhatever] Dead since new update (Issue #137)


I'm sorry, but I don't have enough time now to support the client beta. Maybe in the future.

**Comment by saulgonber** [comment]
Hey, is there any news about when it will work again? I'm looking forward to it working again! 😊

**Comment by m4dEngi** [comment]
Try the latest version.
