### ISSUE TITLE
RPW Crashing after the new Steam Client update

### ISSUE THREAD

**Issue by crudyy** [m4dEngi/RemotePlayWhatever#145]
It's the same as usual. The RPW application keeps crashing after clicking on the friend's list. And this came right after June 13th Steam Client Update. Can you look into this?

**Comment by KOTOKZ7** [comment]
Same thing for me, yesterday everything was fine...

**Comment by mintwzy** [comment]
I did some debugging and noticed the error is from [this ](https://github.com/m4dEngi/RemotePlayWhatever/blob/1c2a202537a218d7b4a8ec950ffef30239041ec8/RemotePlayWhatever/RemotePlayInviteHandler.cpp#L27)line whe calling
```cpp
BCreateRemotePlayInviteAndSession(rppInvitee, gameID.AppID());
```
And it comes from open-steamworks [here](https://github.com/m4dEngi/open-steamworks/blob/65af9cdab5aa9f182fabbe57edba72885e8de0d2/OpenSteamworks/Interfaces/Client/IClientRemoteClientManager.h#L108).

I don't know what next step should be since I am not familiar with C++ or Steam APIs...

**Comment by crudyy** [comment]
> I don't know what next step should be since I am not familiar with C++ or Steam APIs...

I guess we just wait till @m4dEngi does the Lord's work.

**Comment by m4dEngi** [comment]
New version out, sorry it took so long.

**Comment by crudyy** [comment]
> New version out, sorry it took so long.

Ayee, appreciate this a lot! Also don't apologise for it, we owe you one! <3
