### ISSUE TITLE
Friend doesn't see the RPT invite

### ISSUE THREAD

**Issue by radical6** [m4dEngi/RemotePlayWhatever#31]
The RPT window shows up on my (host) end but my Steam friend doesn't see the Remote Play Together invite.

**Comment by m4dEngi** [comment]
This might take some time to fix. The bug is caused by steamclient api changes, callback id changes to be precise.

But until it is fixed you can try to work around this bug by creating RPT invite link and sending it to a friend instead of sending invite to a friend directly. https://github.com/m4dEngi/RemotePlayWhatever/discussions/30
