### ISSUE TITLE
The systray icon seems to be broken on GNOME

### ISSUE THREAD

**Issue by Kirottu** [m4dEngi/RemotePlayWhatever#52]
The systray icon seems to be broken, even though I have an extension to bring back the systray. It just errors out with:
` Gtk-CRITICAL **: 17:31:09.462: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`

**Comment by m4dEngi** [comment]
What's the gnome version in question?

**Comment by Kirottu** [comment]
It is the latest, Gnome 42.1.

**Comment by BulletBlaster** [comment]
I have the same issue on KDE Plasma 5.25.0

**Comment by esotericist** [comment]
the reliance on a systray icon seems strange to me. i was hoping to use app this with my chromebook (running steam in a container), but there's nothing to bridge systray icons and the outward ui so even if the systray icon worked i wouldn't be able to use it.

**Comment by m4dEngi** [comment]
Tray icon is easier to implement and works just fine for me, that's why it's like that. ( i'm using Xfce4 and prefer classic desktop and non-containerized software )

Sometimes i forget that modern desktop is mimicking phones, programs now called apps and systray is just for notifications and status icons.

**Comment by Kirottu** [comment]
In my opinion systray icons are fine for tasks like this, but due to issues like this it probably shouldn't be the only means of control.

**Comment by m4dEngi** [comment]
Closing since tray icon is no longer used as UI substitute.
