### ISSUE TITLE
RemotePlayWhatever is broken on 12/1/2022 stable Steam Deck Client update

### ISSUE THREAD

**Issue by joamjoamjoam** [m4dEngi/RemotePlayWhatever#84]
So unlucky to get a stable build the day after you updated it.

**Comment by joamjoamjoam** [comment]
If you can show me where you get the client headers from steam i can probably help you keep steamOSW up to date if you want.

**Comment by m4dEngi** [comment]
It's not like i keep it secret... Client interfaces are tracked and reconstructed based on [this tools](https://github.com/m4dEngi/steamworks_dumper) output. 

Except for IClientEngine interface which requires manual analysis. I remember i promised a little tutorial on how to recover it from steamclient lib, working on it and will post it later in more appropriate project ( osw or osw dumper ) .

Sorry, past two or so months i had no time to maintain anything due to unrelated issues.

**Comment by joamjoamjoam** [comment]
Yeah no problem at all i can wait for the tutorial when you get the time. Valves been updating the steam client pretty frequently so i was just offering my help to maintain the client interface in case your busy with other things. 

Hope all is well and thanks again for making this thing in the first place

**Comment by HadetTheUndying** [comment]
Is there anything I can do to help with this issue? Trying to play some emulators with my brother, but this doesn't work in gamemode currently and looks like someone removed the decky plugin.

**Comment by joamjoamjoam** [comment]
> Is there anything I can do to help with this issue? Trying to play some emulators with my brother, but this doesn't work in gamemode currently and looks like someone removed the decky plugin.

Hey sorry for the delay. Unfortunately the project this plugin relies on seems to be abandoned. There were some potential workarounds but they all had serious drawbacks that made them unviable. (Sound not being shared saves being overwritten etc). If a viable alternative presents itself ill revive this plugin.
